### ISSUE TITLE
Homegar Admin MAX! CUL Gateway field descriptions

### ISSUE THREAD

**Issue by BiasF** [Homegear/homegear-ui#5]
If you try to create a MAX! Gateway, you don't see the correct field descriptions.
Language doesn't matter (If I switch to english it's the same)

![image](https://user-images.githubusercontent.com/5191818/94598284-05740300-028f-11eb-99b6-ba809ee8fc2a.png)

**Comment by hfedcba** [comment]
Thanks. It's fixed in the next nightly. Intertechno and HomeMatic Wired had the same problem.
